# Generated by Django 4.1.3 on 2022-11-23 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFamilia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='Integrantes1',
            name='nombre',
            field=models.CharField(max_length=250),
        ),
    ]
